<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Shoko.Plugin.NfoGenerator.SelfCheck</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shoko.Plugin.NfoGenerator\Shoko.Plugin.NfoGenerator.csproj" />
    <PackageReference Include="Shoko.Abstractions" Version="6.0.0-alpha.77" />
    <PackageReference Include="Shoko.QueueProcessor" Version="6.0.0-alpha.6" />
  </ItemGroup>

</Project>
